syntax = "proto3";

option csharp_namespace = "GrpcGreeterService";

package greet;

// The greeting service definition
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply);
  
  // Sends multiple greetings
  rpc SayHelloToMany (stream HelloRequest) returns (stream HelloReply);
  
  // Get server info
  rpc GetServerInfo (Empty) returns (ServerInfo);
}

// The request message containing the user's name
message HelloRequest {
  string name = 1;
  string message = 2;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
  int32 timestamp = 2;
}

// Empty message
message Empty {}

// Server information
message ServerInfo {
  string version = 1;
  string environment = 2;
  int64 startup_time = 3;
}
