# the events block is required
events{}

http {
    # include the default mime.types to map file extensions to MIME types
    include /etc/nginx/mime.types;

    server {
        listen 80;
        server_name your_domain.com; # Replace with your domain or IP

        root /usr/share/nginx/html; # Path to your built Angular app's 'dist' folder
        index index.html;

        location / {
            try_files $uri $uri/ /index.html =404;
        }
    }
}