#!/bin/bash

# Make scripts executable
chmod +x setup.sh
chmod +x test_api.sh

echo "🚀 Quick Start Guide"
echo "==================="
echo ""
echo "1. Install Ollama (if not already installed):"
echo "   curl -fsSL https://ollama.com/install.sh | sh"
echo ""
echo "2. Start Ollama service:"
echo "   ollama serve"
echo ""  
echo "3. Pull required model:"
echo "   ollama pull llama3.1:8b"
echo "   # Or for optimized tool calling:"
echo "   ollama pull arcee-agent:7b"
echo ""
echo "4. Set up Python environment:"
echo "   ./setup.sh"
echo ""
echo "5. Activate virtual environment:"
echo "   source venv/bin/activate"
echo ""
echo "6. Start the API server:"
echo "   python main.py"
echo ""
echo "7. Test the API:"
echo "   ./test_api.sh"
echo ""
echo "8. Access the API documentation:"
echo "   Open http://localhost:8000/docs in your browser"
echo ""
echo "🌍 Supported European Cities:"
echo "- Amsterdam, Netherlands"
echo "- Paris, France" 
echo "- Berlin, Germany"
echo "- London, United Kingdom"
echo "- Barcelona, Spain"
echo "- Madrid, Spain"
echo ""
echo "💡 Example API calls:"
echo ""
echo "# Chat with the agent"
echo "curl -X POST http://localhost:8000/api/chat \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"message\": \"I want to rent a bike in Amsterdam\"}'"
echo ""  
echo "# Find bike stations"
echo "curl -X POST http://localhost:8000/api/find-bikes \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"city\": \"Paris\", \"location\": \"Eiffel Tower\", \"max_distance_km\": 2.0}'"
echo ""
echo "Happy cycling! 🚲"
